// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_mu_surv
List calc_mu_surv(List X, List Y, List Z, List inv_omega, List K, arma::mat D, arma::vec beta, arma::vec phi, arma::vec eta, int nK);
RcppExport SEXP _JEL_calc_mu_surv(SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP inv_omegaSEXP, SEXP KSEXP, SEXP DSEXP, SEXP betaSEXP, SEXP phiSEXP, SEXP etaSEXP, SEXP nKSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< List >::type inv_omega(inv_omegaSEXP);
    Rcpp::traits::input_parameter< List >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< int >::type nK(nKSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_mu_surv(X, Y, Z, inv_omega, K, D, beta, phi, eta, nK));
    return rcpp_result_gen;
END_RCPP
}
// calc_Sigma2_surv
List calc_Sigma2_surv(List X, List Z, List inv_omega, arma::mat D, arma::vec eta);
RcppExport SEXP _JEL_calc_Sigma2_surv(SEXP XSEXP, SEXP ZSEXP, SEXP inv_omegaSEXP, SEXP DSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< List >::type inv_omega(inv_omegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_Sigma2_surv(X, Z, inv_omega, D, eta));
    return rcpp_result_gen;
END_RCPP
}
// calc_mu_surv_noX
List calc_mu_surv_noX(List Y, List Z, List inv_omega, List K, const arma::mat& D, const arma::vec& phi, const arma::vec& eta, List c);
RcppExport SEXP _JEL_calc_mu_surv_noX(SEXP YSEXP, SEXP ZSEXP, SEXP inv_omegaSEXP, SEXP KSEXP, SEXP DSEXP, SEXP phiSEXP, SEXP etaSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< List >::type inv_omega(inv_omegaSEXP);
    Rcpp::traits::input_parameter< List >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< List >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_mu_surv_noX(Y, Z, inv_omega, K, D, phi, eta, c));
    return rcpp_result_gen;
END_RCPP
}
// calc_Sigma2_surv_noX
List calc_Sigma2_surv_noX(List Z, List inv_omega, const arma::mat& D, const arma::vec& eta);
RcppExport SEXP _JEL_calc_Sigma2_surv_noX(SEXP ZSEXP, SEXP inv_omegaSEXP, SEXP DSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< List >::type inv_omega(inv_omegaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_Sigma2_surv_noX(Z, inv_omega, D, eta));
    return rcpp_result_gen;
END_RCPP
}
// calc_mu_surv_noX_tv
List calc_mu_surv_noX_tv(List Y, List Z, List inv_omega, List K, const arma::mat& D, const arma::vec& phi, List etaBB, List c);
RcppExport SEXP _JEL_calc_mu_surv_noX_tv(SEXP YSEXP, SEXP ZSEXP, SEXP inv_omegaSEXP, SEXP KSEXP, SEXP DSEXP, SEXP phiSEXP, SEXP etaBBSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< List >::type inv_omega(inv_omegaSEXP);
    Rcpp::traits::input_parameter< List >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< List >::type etaBB(etaBBSEXP);
    Rcpp::traits::input_parameter< List >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_mu_surv_noX_tv(Y, Z, inv_omega, K, D, phi, etaBB, c));
    return rcpp_result_gen;
END_RCPP
}
// calc_Sigma2_surv_noX_tv
List calc_Sigma2_surv_noX_tv(List Z, List inv_omega, const arma::mat& D, List etaBB);
RcppExport SEXP _JEL_calc_Sigma2_surv_noX_tv(SEXP ZSEXP, SEXP inv_omegaSEXP, SEXP DSEXP, SEXP etaBBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< List >::type inv_omega(inv_omegaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< List >::type etaBB(etaBBSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_Sigma2_surv_noX_tv(Z, inv_omega, D, etaBB));
    return rcpp_result_gen;
END_RCPP
}
// Eetaphi_lla_tv
double Eetaphi_lla_tv(arma::vec etaphi, List Y, List Z, List inv_omega, List K, arma::mat D, arma::vec l0i, List l0u, arma::vec Di, int nK, arma::vec w, arma::vec v, List mu_surv, List Sigma2_surv, const List& BBi, const arma::vec& etaInd, List c_list);
RcppExport SEXP _JEL_Eetaphi_lla_tv(SEXP etaphiSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP inv_omegaSEXP, SEXP KSEXP, SEXP DSEXP, SEXP l0iSEXP, SEXP l0uSEXP, SEXP DiSEXP, SEXP nKSEXP, SEXP wSEXP, SEXP vSEXP, SEXP mu_survSEXP, SEXP Sigma2_survSEXP, SEXP BBiSEXP, SEXP etaIndSEXP, SEXP c_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type etaphi(etaphiSEXP);
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< List >::type inv_omega(inv_omegaSEXP);
    Rcpp::traits::input_parameter< List >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< List >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Di(DiSEXP);
    Rcpp::traits::input_parameter< int >::type nK(nKSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< List >::type mu_surv(mu_survSEXP);
    Rcpp::traits::input_parameter< List >::type Sigma2_surv(Sigma2_survSEXP);
    Rcpp::traits::input_parameter< const List& >::type BBi(BBiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type etaInd(etaIndSEXP);
    Rcpp::traits::input_parameter< List >::type c_list(c_listSEXP);
    rcpp_result_gen = Rcpp::wrap(Eetaphi_lla_tv(etaphi, Y, Z, inv_omega, K, D, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, BBi, etaInd, c_list));
    return rcpp_result_gen;
END_RCPP
}
// Setaphi_lla_tv
arma::vec Setaphi_lla_tv(arma::vec etaphi, List Y, List Z, List inv_omega, List K, arma::mat D, arma::vec l0i, List l0u, arma::vec Di, int nK, arma::vec w, arma::vec v, List mu_surv, List Sigma2_surv, const List& BBi, const arma::vec& etaInd, double eps, List c_list);
RcppExport SEXP _JEL_Setaphi_lla_tv(SEXP etaphiSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP inv_omegaSEXP, SEXP KSEXP, SEXP DSEXP, SEXP l0iSEXP, SEXP l0uSEXP, SEXP DiSEXP, SEXP nKSEXP, SEXP wSEXP, SEXP vSEXP, SEXP mu_survSEXP, SEXP Sigma2_survSEXP, SEXP BBiSEXP, SEXP etaIndSEXP, SEXP epsSEXP, SEXP c_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type etaphi(etaphiSEXP);
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< List >::type inv_omega(inv_omegaSEXP);
    Rcpp::traits::input_parameter< List >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< List >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Di(DiSEXP);
    Rcpp::traits::input_parameter< int >::type nK(nKSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< List >::type mu_surv(mu_survSEXP);
    Rcpp::traits::input_parameter< List >::type Sigma2_surv(Sigma2_survSEXP);
    Rcpp::traits::input_parameter< const List& >::type BBi(BBiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type etaInd(etaIndSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< List >::type c_list(c_listSEXP);
    rcpp_result_gen = Rcpp::wrap(Setaphi_lla_tv(etaphi, Y, Z, inv_omega, K, D, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, BBi, etaInd, eps, c_list));
    return rcpp_result_gen;
END_RCPP
}
// Hetaphi_lla_tv
arma::mat Hetaphi_lla_tv(arma::vec etaphi, List Y, List Z, List inv_omega, List K, arma::mat D, arma::vec l0i, List l0u, arma::vec Di, int nK, arma::vec w, arma::vec v, List mu_surv, List Sigma2_surv, const List& BBi, const arma::vec& etaInd, double eps, List c_list);
RcppExport SEXP _JEL_Hetaphi_lla_tv(SEXP etaphiSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP inv_omegaSEXP, SEXP KSEXP, SEXP DSEXP, SEXP l0iSEXP, SEXP l0uSEXP, SEXP DiSEXP, SEXP nKSEXP, SEXP wSEXP, SEXP vSEXP, SEXP mu_survSEXP, SEXP Sigma2_survSEXP, SEXP BBiSEXP, SEXP etaIndSEXP, SEXP epsSEXP, SEXP c_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type etaphi(etaphiSEXP);
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< List >::type inv_omega(inv_omegaSEXP);
    Rcpp::traits::input_parameter< List >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< List >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Di(DiSEXP);
    Rcpp::traits::input_parameter< int >::type nK(nKSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< List >::type mu_surv(mu_survSEXP);
    Rcpp::traits::input_parameter< List >::type Sigma2_surv(Sigma2_survSEXP);
    Rcpp::traits::input_parameter< const List& >::type BBi(BBiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type etaInd(etaIndSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< List >::type c_list(c_listSEXP);
    rcpp_result_gen = Rcpp::wrap(Hetaphi_lla_tv(etaphi, Y, Z, inv_omega, K, D, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, BBi, etaInd, eps, c_list));
    return rcpp_result_gen;
END_RCPP
}
// calc_mu_surv_tv
List calc_mu_surv_tv(List X, List Y, List Z, List inv_omega, List K, arma::mat D, arma::vec beta, arma::vec phi, List etaBB, int nK);
RcppExport SEXP _JEL_calc_mu_surv_tv(SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP inv_omegaSEXP, SEXP KSEXP, SEXP DSEXP, SEXP betaSEXP, SEXP phiSEXP, SEXP etaBBSEXP, SEXP nKSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< List >::type inv_omega(inv_omegaSEXP);
    Rcpp::traits::input_parameter< List >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< List >::type etaBB(etaBBSEXP);
    Rcpp::traits::input_parameter< int >::type nK(nKSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_mu_surv_tv(X, Y, Z, inv_omega, K, D, beta, phi, etaBB, nK));
    return rcpp_result_gen;
END_RCPP
}
// calc_Sigma2_surv_tv
List calc_Sigma2_surv_tv(List X, List Z, List inv_omega, arma::mat D, List etaBB);
RcppExport SEXP _JEL_calc_Sigma2_surv_tv(SEXP XSEXP, SEXP ZSEXP, SEXP inv_omegaSEXP, SEXP DSEXP, SEXP etaBBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< List >::type inv_omega(inv_omegaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< List >::type etaBB(etaBBSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_Sigma2_surv_tv(X, Z, inv_omega, D, etaBB));
    return rcpp_result_gen;
END_RCPP
}
// subtract_one_from_uvec
arma::uvec subtract_one_from_uvec(arma::uvec vec);
RcppExport SEXP _JEL_subtract_one_from_uvec(SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uvec >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(subtract_one_from_uvec(vec));
    return rcpp_result_gen;
END_RCPP
}
// calc_inv_omega_kernel
List calc_inv_omega_kernel(List mi_list, arma::vec var_e, List w_stack_list);
RcppExport SEXP _JEL_calc_inv_omega_kernel(SEXP mi_listSEXP, SEXP var_eSEXP, SEXP w_stack_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mi_list(mi_listSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type var_e(var_eSEXP);
    Rcpp::traits::input_parameter< List >::type w_stack_list(w_stack_listSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_inv_omega_kernel(mi_list, var_e, w_stack_list));
    return rcpp_result_gen;
END_RCPP
}
// calc_Sigma_longK
List calc_Sigma_longK(List Z_list, List S_list, int nK);
RcppExport SEXP _JEL_calc_Sigma_longK(SEXP Z_listSEXP, SEXP S_listSEXP, SEXP nKSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Z_list(Z_listSEXP);
    Rcpp::traits::input_parameter< List >::type S_list(S_listSEXP);
    Rcpp::traits::input_parameter< int >::type nK(nKSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_Sigma_longK(Z_list, S_list, nK));
    return rcpp_result_gen;
END_RCPP
}
// calc_mu_longK_noX
List calc_mu_longK_noX(List Y_list, List Z_list, List b_list, List b_inds, int nK);
RcppExport SEXP _JEL_calc_mu_longK_noX(SEXP Y_listSEXP, SEXP Z_listSEXP, SEXP b_listSEXP, SEXP b_indsSEXP, SEXP nKSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Y_list(Y_listSEXP);
    Rcpp::traits::input_parameter< List >::type Z_list(Z_listSEXP);
    Rcpp::traits::input_parameter< List >::type b_list(b_listSEXP);
    Rcpp::traits::input_parameter< List >::type b_inds(b_indsSEXP);
    Rcpp::traits::input_parameter< int >::type nK(nKSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_mu_longK_noX(Y_list, Z_list, b_list, b_inds, nK));
    return rcpp_result_gen;
END_RCPP
}
// calc_Ee_kernel
List calc_Ee_kernel(List mu_list, List Sigma_longK, List w_longK, int nK);
RcppExport SEXP _JEL_calc_Ee_kernel(SEXP mu_listSEXP, SEXP Sigma_longKSEXP, SEXP w_longKSEXP, SEXP nKSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mu_list(mu_listSEXP);
    Rcpp::traits::input_parameter< List >::type Sigma_longK(Sigma_longKSEXP);
    Rcpp::traits::input_parameter< List >::type w_longK(w_longKSEXP);
    Rcpp::traits::input_parameter< int >::type nK(nKSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_Ee_kernel(mu_list, Sigma_longK, w_longK, nK));
    return rcpp_result_gen;
END_RCPP
}
// calc_M1_M2_Hadamard
void calc_M1_M2_Hadamard(Eigen::Map<Eigen::ArrayXd>& M1, const Eigen::Map<Eigen::ArrayXd>& M2);
RcppExport SEXP _JEL_calc_M1_M2_Hadamard(SEXP M1SEXP, SEXP M2SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::ArrayXd>& >::type M1(M1SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXd>& >::type M2(M2SEXP);
    calc_M1_M2_Hadamard(M1, M2);
    return R_NilValue;
END_RCPP
}
// calc_M1_M2_Hadamard_a
Eigen::MatrixXd calc_M1_M2_Hadamard_a(Eigen::Map<Eigen::ArrayXXd>& A1, const Eigen::Map<Eigen::ArrayXXd>& A2, const Eigen::Map<Eigen::VectorXd>& v3, const int a);
RcppExport SEXP _JEL_calc_M1_M2_Hadamard_a(SEXP A1SEXP, SEXP A2SEXP, SEXP v3SEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::ArrayXXd>& >::type A1(A1SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXXd>& >::type A2(A2SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type v3(v3SEXP);
    Rcpp::traits::input_parameter< const int >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_M1_M2_Hadamard_a(A1, A2, v3, a));
    return rcpp_result_gen;
END_RCPP
}
// calc_M1_M2_M3_Hadamard
void calc_M1_M2_M3_Hadamard(Eigen::Map<Eigen::MatrixXd>& M1, const Eigen::Map<Eigen::MatrixXd>& M2, const Eigen::Map<Eigen::MatrixXd>& M3, const Eigen::Map<Eigen::VectorXi>& v);
RcppExport SEXP _JEL_calc_M1_M2_M3_Hadamard(SEXP M1SEXP, SEXP M2SEXP, SEXP M3SEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type M1(M1SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type M2(M2SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type M3(M3SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXi>& >::type v(vSEXP);
    calc_M1_M2_M3_Hadamard(M1, M2, M3, v);
    return R_NilValue;
END_RCPP
}
// calc_M1_a_M2_Hadamard
void calc_M1_a_M2_Hadamard(Eigen::Map<Eigen::MatrixXd>& M1, const Eigen::Map<Eigen::MatrixXd>& M2, const double a, const Eigen::Map<Eigen::VectorXi>& v);
RcppExport SEXP _JEL_calc_M1_a_M2_Hadamard(SEXP M1SEXP, SEXP M2SEXP, SEXP aSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type M1(M1SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type M2(M2SEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXi>& >::type v(vSEXP);
    calc_M1_a_M2_Hadamard(M1, M2, a, v);
    return R_NilValue;
END_RCPP
}
// calc_M1timesM2v
Eigen::MatrixXd calc_M1timesM2v(const Eigen::Map<Eigen::MatrixXd>& M1, const Eigen::Map<Eigen::MatrixXd>& M2, const Eigen::Map<Eigen::ArrayXd>& v);
RcppExport SEXP _JEL_calc_M1timesM2v(SEXP M1SEXP, SEXP M2SEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type M1(M1SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type M2(M2SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXd>& >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_M1timesM2v(M1, M2, v));
    return rcpp_result_gen;
END_RCPP
}
// calc_MVND
double calc_MVND(const Eigen::Map<Eigen::VectorXd>& x, const Eigen::Map<Eigen::VectorXd>& mu, const Eigen::Map<Eigen::MatrixXd>& K);
RcppExport SEXP _JEL_calc_MVND(SEXP xSEXP, SEXP muSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_MVND(x, mu, K));
    return rcpp_result_gen;
END_RCPP
}
// calc_M_v
Eigen::VectorXd calc_M_v(const Eigen::Map<Eigen::VectorXd>& v, const Eigen::Map<Eigen::MatrixXd>& M);
RcppExport SEXP _JEL_calc_M_v(SEXP vSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_M_v(v, M));
    return rcpp_result_gen;
END_RCPP
}
// calc_VB
Eigen::MatrixXd calc_VB(const Eigen::Map<Eigen::MatrixXd>& M1, const Eigen::Map<Eigen::MatrixXd>& M2, const Eigen::Map<Eigen::MatrixXd>& M3);
RcppExport SEXP _JEL_calc_VB(SEXP M1SEXP, SEXP M2SEXP, SEXP M3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type M1(M1SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type M2(M2SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type M3(M3SEXP);
    rcpp_result_gen = Rcpp::wrap(calc_VB(M1, M2, M3));
    return rcpp_result_gen;
END_RCPP
}
// calc_VY
Eigen::MatrixXd calc_VY(const Eigen::Map<Eigen::MatrixXd>& M, const Eigen::Map<Eigen::MatrixXd>& A, const double b);
RcppExport SEXP _JEL_calc_VY(SEXP MSEXP, SEXP ASEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_VY(M, A, b));
    return rcpp_result_gen;
END_RCPP
}
// calc_bi_st
Eigen::MatrixXd calc_bi_st(const Eigen::Map<Eigen::VectorXd>& v0, const Eigen::Map<Eigen::MatrixXd>& m, const Eigen::Map<Eigen::MatrixXd>& M);
RcppExport SEXP _JEL_calc_bi_st(SEXP v0SEXP, SEXP mSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type v0(v0SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_bi_st(v0, m, M));
    return rcpp_result_gen;
END_RCPP
}
// calc_expM2
void calc_expM2(Eigen::Map<Eigen::ArrayXd>& A);
RcppExport SEXP _JEL_calc_expM2(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::ArrayXd>& >::type A(ASEXP);
    calc_expM2(A);
    return R_NilValue;
END_RCPP
}
// calc_muB
Eigen::MatrixXd calc_muB(const Eigen::Map<Eigen::MatrixXd>& BSold, const Eigen::Map<Eigen::MatrixXd>& VY, const Eigen::Map<Eigen::MatrixXd>& Xst, const Eigen::Map<Eigen::MatrixXd>& Zst, const Eigen::Map<Eigen::VectorXd>& Yst, const Eigen::Map<Eigen::VectorXd>& betaold);
RcppExport SEXP _JEL_calc_muB(SEXP BSoldSEXP, SEXP VYSEXP, SEXP XstSEXP, SEXP ZstSEXP, SEXP YstSEXP, SEXP betaoldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type BSold(BSoldSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type VY(VYSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type Xst(XstSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type Zst(ZstSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type Yst(YstSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type betaold(betaoldSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_muB(BSold, VY, Xst, Zst, Yst, betaold));
    return rcpp_result_gen;
END_RCPP
}
// calc_muBMult
Eigen::VectorXd calc_muBMult(const Eigen::Map<Eigen::MatrixXd>& BSold, const Eigen::Map<Eigen::MatrixXd>& VY, const Eigen::Map<Eigen::VectorXd>& BTg, const Eigen::Map<Eigen::VectorXd>& Yst);
RcppExport SEXP _JEL_calc_muBMult(SEXP BSoldSEXP, SEXP VYSEXP, SEXP BTgSEXP, SEXP YstSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type BSold(BSoldSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type VY(VYSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type BTg(BTgSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type Yst(YstSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_muBMult(BSold, VY, BTg, Yst));
    return rcpp_result_gen;
END_RCPP
}
// calc_mult_rowsum1
Eigen::MatrixXd calc_mult_rowsum1(const Eigen::Map<Eigen::VectorXi>& v, const Eigen::Map<Eigen::VectorXd>& u, const Eigen::Map<Eigen::MatrixXd>& M, const Eigen::Map<Eigen::ArrayXXd>& A);
RcppExport SEXP _JEL_calc_mult_rowsum1(SEXP vSEXP, SEXP uSEXP, SEXP MSEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXi>& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXXd>& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(calc_mult_rowsum1(v, u, M, A));
    return rcpp_result_gen;
END_RCPP
}
// calc_mult_rowsum2
Eigen::MatrixXd calc_mult_rowsum2(const Eigen::Map<Eigen::VectorXi>& v, const Eigen::Map<Eigen::MatrixXd>& L, const Eigen::Map<Eigen::MatrixXd>& M, const Eigen::Map<Eigen::ArrayXXd>& A);
RcppExport SEXP _JEL_calc_mult_rowsum2(SEXP vSEXP, SEXP LSEXP, SEXP MSEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXi>& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXXd>& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(calc_mult_rowsum2(v, L, M, A));
    return rcpp_result_gen;
END_RCPP
}
// calc_mult_rowsum3
Rcpp::List calc_mult_rowsum3(const Eigen::Map<Eigen::ArrayXi>& v, const Eigen::Map<Eigen::ArrayXXd>& B, const Eigen::Map<Eigen::ArrayXXd>& M, const Eigen::Map<Eigen::ArrayXXd>& A, const double ncb2);
RcppExport SEXP _JEL_calc_mult_rowsum3(SEXP vSEXP, SEXP BSEXP, SEXP MSEXP, SEXP ASEXP, SEXP ncb2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXi>& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXXd>& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXXd>& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXXd>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const double >::type ncb2(ncb2SEXP);
    rcpp_result_gen = Rcpp::wrap(calc_mult_rowsum3(v, B, M, A, ncb2));
    return rcpp_result_gen;
END_RCPP
}
// calc_rowsum
Eigen::MatrixXd calc_rowsum(const Eigen::Map<Eigen::VectorXi>& v, const Eigen::Map<Eigen::MatrixXd>& M);
RcppExport SEXP _JEL_calc_rowsum(SEXP vSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXi>& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_rowsum(v, M));
    return rcpp_result_gen;
END_RCPP
}
// calc_rowsum_mult
Eigen::MatrixXd calc_rowsum_mult(const Eigen::Map<Eigen::VectorXi>& v, const Eigen::Map<Eigen::VectorXd>& u, const Eigen::Map<Eigen::MatrixXd>& M);
RcppExport SEXP _JEL_calc_rowsum_mult(SEXP vSEXP, SEXP uSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXi>& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_rowsum_mult(v, u, M));
    return rcpp_result_gen;
END_RCPP
}
// calc_tapply_vect_sum
Eigen::ArrayXd calc_tapply_vect_sum(const Eigen::Map<Eigen::ArrayXd>& v1, const Eigen::Map<Eigen::ArrayXi>& v2);
RcppExport SEXP _JEL_calc_tapply_vect_sum(SEXP v1SEXP, SEXP v2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXd>& >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::ArrayXi>& >::type v2(v2SEXP);
    rcpp_result_gen = Rcpp::wrap(calc_tapply_vect_sum(v1, v2));
    return rcpp_result_gen;
END_RCPP
}
// calc_v_a
void calc_v_a(Eigen::Map<Eigen::ArrayXd>& v, const double& a);
RcppExport SEXP _JEL_calc_v_a(SEXP vSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::ArrayXd>& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    calc_v_a(v, a);
    return R_NilValue;
END_RCPP
}
// Esurv
arma::vec Esurv(arma::vec w, arma::vec v, List mu, List variance, List mu_new, List variance_new, arma::vec l0i, List l0u);
RcppExport SEXP _JEL_Esurv(SEXP wSEXP, SEXP vSEXP, SEXP muSEXP, SEXP varianceSEXP, SEXP mu_newSEXP, SEXP variance_newSEXP, SEXP l0iSEXP, SEXP l0uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< List >::type mu(muSEXP);
    Rcpp::traits::input_parameter< List >::type variance(varianceSEXP);
    Rcpp::traits::input_parameter< List >::type mu_new(mu_newSEXP);
    Rcpp::traits::input_parameter< List >::type variance_new(variance_newSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< List >::type l0u(l0uSEXP);
    rcpp_result_gen = Rcpp::wrap(Esurv(w, v, mu, variance, mu_new, variance_new, l0i, l0u));
    return rcpp_result_gen;
END_RCPP
}
// Esurv_exp
arma::vec Esurv_exp(arma::vec w, arma::vec v, List mu, List variance, List mu_new, List variance_new, arma::vec l0i, List l0u);
RcppExport SEXP _JEL_Esurv_exp(SEXP wSEXP, SEXP vSEXP, SEXP muSEXP, SEXP varianceSEXP, SEXP mu_newSEXP, SEXP variance_newSEXP, SEXP l0iSEXP, SEXP l0uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< List >::type mu(muSEXP);
    Rcpp::traits::input_parameter< List >::type variance(varianceSEXP);
    Rcpp::traits::input_parameter< List >::type mu_new(mu_newSEXP);
    Rcpp::traits::input_parameter< List >::type variance_new(variance_newSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< List >::type l0u(l0uSEXP);
    rcpp_result_gen = Rcpp::wrap(Esurv_exp(w, v, mu, variance, mu_new, variance_new, l0i, l0u));
    return rcpp_result_gen;
END_RCPP
}
// Eetaphi
double Eetaphi(arma::vec etaphi, List Y, List Z, List inv_omega, List K, arma::mat D, arma::vec l0i, List l0u, arma::vec Di, int nK, arma::vec w, arma::vec v, List mu_surv, List Sigma2_surv, List c_list);
RcppExport SEXP _JEL_Eetaphi(SEXP etaphiSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP inv_omegaSEXP, SEXP KSEXP, SEXP DSEXP, SEXP l0iSEXP, SEXP l0uSEXP, SEXP DiSEXP, SEXP nKSEXP, SEXP wSEXP, SEXP vSEXP, SEXP mu_survSEXP, SEXP Sigma2_survSEXP, SEXP c_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type etaphi(etaphiSEXP);
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< List >::type inv_omega(inv_omegaSEXP);
    Rcpp::traits::input_parameter< List >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< List >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Di(DiSEXP);
    Rcpp::traits::input_parameter< int >::type nK(nKSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< List >::type mu_surv(mu_survSEXP);
    Rcpp::traits::input_parameter< List >::type Sigma2_surv(Sigma2_survSEXP);
    Rcpp::traits::input_parameter< List >::type c_list(c_listSEXP);
    rcpp_result_gen = Rcpp::wrap(Eetaphi(etaphi, Y, Z, inv_omega, K, D, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, c_list));
    return rcpp_result_gen;
END_RCPP
}
// Setaphi
arma::vec Setaphi(arma::vec etaphi, List Y, List Z, List inv_omega, List K, arma::mat D, arma::vec l0i, List l0u, arma::vec Di, int nK, arma::vec w, arma::vec v, List mu_surv, List Sigma2_surv, double eps, List c_list);
RcppExport SEXP _JEL_Setaphi(SEXP etaphiSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP inv_omegaSEXP, SEXP KSEXP, SEXP DSEXP, SEXP l0iSEXP, SEXP l0uSEXP, SEXP DiSEXP, SEXP nKSEXP, SEXP wSEXP, SEXP vSEXP, SEXP mu_survSEXP, SEXP Sigma2_survSEXP, SEXP epsSEXP, SEXP c_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type etaphi(etaphiSEXP);
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< List >::type inv_omega(inv_omegaSEXP);
    Rcpp::traits::input_parameter< List >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< List >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Di(DiSEXP);
    Rcpp::traits::input_parameter< int >::type nK(nKSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< List >::type mu_surv(mu_survSEXP);
    Rcpp::traits::input_parameter< List >::type Sigma2_surv(Sigma2_survSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< List >::type c_list(c_listSEXP);
    rcpp_result_gen = Rcpp::wrap(Setaphi(etaphi, Y, Z, inv_omega, K, D, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, eps, c_list));
    return rcpp_result_gen;
END_RCPP
}
// Setaphi_perobs
arma::mat Setaphi_perobs(arma::vec etaphi, List Y, List Z, List inv_omega, List K, arma::mat D, arma::vec l0i, List l0u, arma::vec Di, int nK, arma::vec w, arma::vec v, List mu_surv, List Sigma2_surv, double eps, List c_list);
RcppExport SEXP _JEL_Setaphi_perobs(SEXP etaphiSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP inv_omegaSEXP, SEXP KSEXP, SEXP DSEXP, SEXP l0iSEXP, SEXP l0uSEXP, SEXP DiSEXP, SEXP nKSEXP, SEXP wSEXP, SEXP vSEXP, SEXP mu_survSEXP, SEXP Sigma2_survSEXP, SEXP epsSEXP, SEXP c_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type etaphi(etaphiSEXP);
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< List >::type inv_omega(inv_omegaSEXP);
    Rcpp::traits::input_parameter< List >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< List >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Di(DiSEXP);
    Rcpp::traits::input_parameter< int >::type nK(nKSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< List >::type mu_surv(mu_survSEXP);
    Rcpp::traits::input_parameter< List >::type Sigma2_surv(Sigma2_survSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< List >::type c_list(c_listSEXP);
    rcpp_result_gen = Rcpp::wrap(Setaphi_perobs(etaphi, Y, Z, inv_omega, K, D, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, eps, c_list));
    return rcpp_result_gen;
END_RCPP
}
// Hetaphi
arma::mat Hetaphi(arma::vec etaphi, List Y, List Z, List inv_omega, List K, arma::mat D, arma::vec l0i, List l0u, arma::vec Di, int nK, arma::vec w, arma::vec v, List mu_surv, List Sigma2_surv, double eps, List c_list);
RcppExport SEXP _JEL_Hetaphi(SEXP etaphiSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP inv_omegaSEXP, SEXP KSEXP, SEXP DSEXP, SEXP l0iSEXP, SEXP l0uSEXP, SEXP DiSEXP, SEXP nKSEXP, SEXP wSEXP, SEXP vSEXP, SEXP mu_survSEXP, SEXP Sigma2_survSEXP, SEXP epsSEXP, SEXP c_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type etaphi(etaphiSEXP);
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< List >::type inv_omega(inv_omegaSEXP);
    Rcpp::traits::input_parameter< List >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< List >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Di(DiSEXP);
    Rcpp::traits::input_parameter< int >::type nK(nKSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< List >::type mu_surv(mu_survSEXP);
    Rcpp::traits::input_parameter< List >::type Sigma2_surv(Sigma2_survSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< List >::type c_list(c_listSEXP);
    rcpp_result_gen = Rcpp::wrap(Hetaphi(etaphi, Y, Z, inv_omega, K, D, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, eps, c_list));
    return rcpp_result_gen;
END_RCPP
}
// scaleMatricesByEta
List scaleMatricesByEta(const List& BBi, const arma::vec& eta);
RcppExport SEXP _JEL_scaleMatricesByEta(SEXP BBiSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type BBi(BBiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(scaleMatricesByEta(BBi, eta));
    return rcpp_result_gen;
END_RCPP
}
// createResultMatrix
arma::mat createResultMatrix(const arma::mat& A, const arma::vec& etaInd);
RcppExport SEXP _JEL_createResultMatrix(SEXP ASEXP, SEXP etaIndSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type etaInd(etaIndSEXP);
    rcpp_result_gen = Rcpp::wrap(createResultMatrix(A, etaInd));
    return rcpp_result_gen;
END_RCPP
}
// etaBBs_compute
List etaBBs_compute(const List& BBi, const arma::vec& eta, const arma::vec& etaInd);
RcppExport SEXP _JEL_etaBBs_compute(SEXP BBiSEXP, SEXP etaSEXP, SEXP etaIndSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type BBi(BBiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type etaInd(etaIndSEXP);
    rcpp_result_gen = Rcpp::wrap(etaBBs_compute(BBi, eta, etaInd));
    return rcpp_result_gen;
END_RCPP
}
// Esurv_tv
arma::vec Esurv_tv(arma::vec w, arma::vec v, List mu, List variance, List mu_new, List variance_new, arma::vec l0i, List l0u);
RcppExport SEXP _JEL_Esurv_tv(SEXP wSEXP, SEXP vSEXP, SEXP muSEXP, SEXP varianceSEXP, SEXP mu_newSEXP, SEXP variance_newSEXP, SEXP l0iSEXP, SEXP l0uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< List >::type mu(muSEXP);
    Rcpp::traits::input_parameter< List >::type variance(varianceSEXP);
    Rcpp::traits::input_parameter< List >::type mu_new(mu_newSEXP);
    Rcpp::traits::input_parameter< List >::type variance_new(variance_newSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< List >::type l0u(l0uSEXP);
    rcpp_result_gen = Rcpp::wrap(Esurv_tv(w, v, mu, variance, mu_new, variance_new, l0i, l0u));
    return rcpp_result_gen;
END_RCPP
}
// Esurv_exp_tv
arma::vec Esurv_exp_tv(arma::vec w, arma::vec v, List mu, List variance, List mu_new, List variance_new, arma::vec l0i, List l0u);
RcppExport SEXP _JEL_Esurv_exp_tv(SEXP wSEXP, SEXP vSEXP, SEXP muSEXP, SEXP varianceSEXP, SEXP mu_newSEXP, SEXP variance_newSEXP, SEXP l0iSEXP, SEXP l0uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< List >::type mu(muSEXP);
    Rcpp::traits::input_parameter< List >::type variance(varianceSEXP);
    Rcpp::traits::input_parameter< List >::type mu_new(mu_newSEXP);
    Rcpp::traits::input_parameter< List >::type variance_new(variance_newSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< List >::type l0u(l0uSEXP);
    rcpp_result_gen = Rcpp::wrap(Esurv_exp_tv(w, v, mu, variance, mu_new, variance_new, l0i, l0u));
    return rcpp_result_gen;
END_RCPP
}
// Esurv_exp_t
List Esurv_exp_t(arma::vec w, arma::vec v, List mu, List variance, List mu_new, List variance_new, arma::vec l0i, List l0u);
RcppExport SEXP _JEL_Esurv_exp_t(SEXP wSEXP, SEXP vSEXP, SEXP muSEXP, SEXP varianceSEXP, SEXP mu_newSEXP, SEXP variance_newSEXP, SEXP l0iSEXP, SEXP l0uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< List >::type mu(muSEXP);
    Rcpp::traits::input_parameter< List >::type variance(varianceSEXP);
    Rcpp::traits::input_parameter< List >::type mu_new(mu_newSEXP);
    Rcpp::traits::input_parameter< List >::type variance_new(variance_newSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< List >::type l0u(l0uSEXP);
    rcpp_result_gen = Rcpp::wrap(Esurv_exp_t(w, v, mu, variance, mu_new, variance_new, l0i, l0u));
    return rcpp_result_gen;
END_RCPP
}
// Eetaphi_t
double Eetaphi_t(arma::vec etaphi, List X, List Y, List Z, List inv_omega, List K, arma::mat D, arma::vec beta, arma::vec l0i, List l0u, arma::vec Di, int nK, arma::vec w, arma::vec v, List mu_surv, List Sigma2_surv, const List& BBi, const arma::vec& etaInd);
RcppExport SEXP _JEL_Eetaphi_t(SEXP etaphiSEXP, SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP inv_omegaSEXP, SEXP KSEXP, SEXP DSEXP, SEXP betaSEXP, SEXP l0iSEXP, SEXP l0uSEXP, SEXP DiSEXP, SEXP nKSEXP, SEXP wSEXP, SEXP vSEXP, SEXP mu_survSEXP, SEXP Sigma2_survSEXP, SEXP BBiSEXP, SEXP etaIndSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type etaphi(etaphiSEXP);
    Rcpp::traits::input_parameter< List >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< List >::type inv_omega(inv_omegaSEXP);
    Rcpp::traits::input_parameter< List >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< List >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Di(DiSEXP);
    Rcpp::traits::input_parameter< int >::type nK(nKSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< List >::type mu_surv(mu_survSEXP);
    Rcpp::traits::input_parameter< List >::type Sigma2_surv(Sigma2_survSEXP);
    Rcpp::traits::input_parameter< const List& >::type BBi(BBiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type etaInd(etaIndSEXP);
    rcpp_result_gen = Rcpp::wrap(Eetaphi_t(etaphi, X, Y, Z, inv_omega, K, D, beta, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, BBi, etaInd));
    return rcpp_result_gen;
END_RCPP
}
// Setaphi_t
arma::vec Setaphi_t(arma::vec etaphi, List X, List Y, List Z, List inv_omega, List K, arma::mat D, arma::vec beta, arma::vec l0i, List l0u, arma::vec Di, int nK, arma::vec w, arma::vec v, List mu_surv, List Sigma2_surv, const List& BBi, const arma::vec& etaInd, double eps);
RcppExport SEXP _JEL_Setaphi_t(SEXP etaphiSEXP, SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP inv_omegaSEXP, SEXP KSEXP, SEXP DSEXP, SEXP betaSEXP, SEXP l0iSEXP, SEXP l0uSEXP, SEXP DiSEXP, SEXP nKSEXP, SEXP wSEXP, SEXP vSEXP, SEXP mu_survSEXP, SEXP Sigma2_survSEXP, SEXP BBiSEXP, SEXP etaIndSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type etaphi(etaphiSEXP);
    Rcpp::traits::input_parameter< List >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< List >::type inv_omega(inv_omegaSEXP);
    Rcpp::traits::input_parameter< List >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< List >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Di(DiSEXP);
    Rcpp::traits::input_parameter< int >::type nK(nKSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< List >::type mu_surv(mu_survSEXP);
    Rcpp::traits::input_parameter< List >::type Sigma2_surv(Sigma2_survSEXP);
    Rcpp::traits::input_parameter< const List& >::type BBi(BBiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type etaInd(etaIndSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(Setaphi_t(etaphi, X, Y, Z, inv_omega, K, D, beta, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, BBi, etaInd, eps));
    return rcpp_result_gen;
END_RCPP
}
// Hetaphi_t
arma::mat Hetaphi_t(arma::vec etaphi, List X, List Y, List Z, List inv_omega, List K, arma::mat D, arma::vec beta, arma::vec l0i, List l0u, arma::vec Di, int nK, arma::vec w, arma::vec v, List mu_surv, List Sigma2_surv, const List& BBi, const arma::vec& etaInd, double eps);
RcppExport SEXP _JEL_Hetaphi_t(SEXP etaphiSEXP, SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP inv_omegaSEXP, SEXP KSEXP, SEXP DSEXP, SEXP betaSEXP, SEXP l0iSEXP, SEXP l0uSEXP, SEXP DiSEXP, SEXP nKSEXP, SEXP wSEXP, SEXP vSEXP, SEXP mu_survSEXP, SEXP Sigma2_survSEXP, SEXP BBiSEXP, SEXP etaIndSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type etaphi(etaphiSEXP);
    Rcpp::traits::input_parameter< List >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< List >::type inv_omega(inv_omegaSEXP);
    Rcpp::traits::input_parameter< List >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< List >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Di(DiSEXP);
    Rcpp::traits::input_parameter< int >::type nK(nKSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< List >::type mu_surv(mu_survSEXP);
    Rcpp::traits::input_parameter< List >::type Sigma2_surv(Sigma2_survSEXP);
    Rcpp::traits::input_parameter< const List& >::type BBi(BBiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type etaInd(etaIndSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(Hetaphi_t(etaphi, X, Y, Z, inv_omega, K, D, beta, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, BBi, etaInd, eps));
    return rcpp_result_gen;
END_RCPP
}
// fast_lapply_length
Eigen::MatrixXd fast_lapply_length(Rcpp::List const input1, Rcpp::List const input2, Rcpp::NumericVector const Ind);
RcppExport SEXP _JEL_fast_lapply_length(SEXP input1SEXP, SEXP input2SEXP, SEXP IndSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List const >::type input1(input1SEXP);
    Rcpp::traits::input_parameter< Rcpp::List const >::type input2(input2SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector const >::type Ind(IndSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_lapply_length(input1, input2, Ind));
    return rcpp_result_gen;
END_RCPP
}
// fast_rbind_lapply_outerprod
Eigen::MatrixXd fast_rbind_lapply_outerprod(Rcpp::List const input);
RcppExport SEXP _JEL_fast_rbind_lapply_outerprod(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List const >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_rbind_lapply_outerprod(input));
    return rcpp_result_gen;
END_RCPP
}
// ll
double ll(arma::vec b, const arma::colvec Y, const arma::mat X, const arma::mat Z, const arma::mat V, const arma::mat D, int mi, const arma::rowvec K, const int Delta, const double l0i, const arma::rowvec l0u, const arma::vec beta, const arma::vec phi, const arma::vec eta, const int nK, const int q);
RcppExport SEXP _JEL_ll(SEXP bSEXP, SEXP YSEXP, SEXP XSEXP, SEXP ZSEXP, SEXP VSEXP, SEXP DSEXP, SEXP miSEXP, SEXP KSEXP, SEXP DeltaSEXP, SEXP l0iSEXP, SEXP l0uSEXP, SEXP betaSEXP, SEXP phiSEXP, SEXP etaSEXP, SEXP nKSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type mi(miSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< const double >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const int >::type nK(nKSEXP);
    Rcpp::traits::input_parameter< const int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(ll(b, Y, X, Z, V, D, mi, K, Delta, l0i, l0u, beta, phi, eta, nK, q));
    return rcpp_result_gen;
END_RCPP
}
// gradll
arma::colvec gradll(arma::vec b, const arma::colvec Y, const arma::mat X, const arma::mat Z, const arma::mat V, const arma::mat D, int mi, const arma::rowvec K, const int Delta, const double l0i, const arma::rowvec l0u, const arma::vec beta, const arma::vec phi, const arma::vec eta, const int nK, const int q);
RcppExport SEXP _JEL_gradll(SEXP bSEXP, SEXP YSEXP, SEXP XSEXP, SEXP ZSEXP, SEXP VSEXP, SEXP DSEXP, SEXP miSEXP, SEXP KSEXP, SEXP DeltaSEXP, SEXP l0iSEXP, SEXP l0uSEXP, SEXP betaSEXP, SEXP phiSEXP, SEXP etaSEXP, SEXP nKSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type mi(miSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< const double >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const int >::type nK(nKSEXP);
    Rcpp::traits::input_parameter< const int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(gradll(b, Y, X, Z, V, D, mi, K, Delta, l0i, l0u, beta, phi, eta, nK, q));
    return rcpp_result_gen;
END_RCPP
}
// sdll
arma::mat sdll(arma::vec b, const arma::mat Z, const arma::mat D, const arma::mat V, const arma::rowvec K, const arma::vec l0u, const arma::vec phi, const arma::vec eta, const int nK);
RcppExport SEXP _JEL_sdll(SEXP bSEXP, SEXP ZSEXP, SEXP DSEXP, SEXP VSEXP, SEXP KSEXP, SEXP l0uSEXP, SEXP phiSEXP, SEXP etaSEXP, SEXP nKSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const int >::type nK(nKSEXP);
    rcpp_result_gen = Rcpp::wrap(sdll(b, Z, D, V, K, l0u, phi, eta, nK));
    return rcpp_result_gen;
END_RCPP
}
// ll_lla
double ll_lla(const arma::vec& b, const arma::colvec& Y, const arma::mat& Z, const arma::mat& V, const arma::mat& D, const int mi, const arma::rowvec& K, const int Delta, const double l0i, const arma::rowvec& l0u, const arma::vec& phi, const arma::vec& eta, const arma::vec& w, const arma::vec& c);
RcppExport SEXP _JEL_ll_lla(SEXP bSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP VSEXP, SEXP DSEXP, SEXP miSEXP, SEXP KSEXP, SEXP DeltaSEXP, SEXP l0iSEXP, SEXP l0uSEXP, SEXP phiSEXP, SEXP etaSEXP, SEXP wSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const int >::type mi(miSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< const double >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(ll_lla(b, Y, Z, V, D, mi, K, Delta, l0i, l0u, phi, eta, w, c));
    return rcpp_result_gen;
END_RCPP
}
// gradll_lla
arma::colvec gradll_lla(const arma::vec& b, const arma::colvec& Y, const arma::mat& Z, const arma::mat& V, const arma::mat& D, const int mi, const arma::rowvec& K, const int Delta, const double l0i, const arma::rowvec& l0u, const arma::vec& phi, const arma::vec& eta, const arma::vec& w, const arma::vec& c);
RcppExport SEXP _JEL_gradll_lla(SEXP bSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP VSEXP, SEXP DSEXP, SEXP miSEXP, SEXP KSEXP, SEXP DeltaSEXP, SEXP l0iSEXP, SEXP l0uSEXP, SEXP phiSEXP, SEXP etaSEXP, SEXP wSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const int >::type mi(miSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< const double >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(gradll_lla(b, Y, Z, V, D, mi, K, Delta, l0i, l0u, phi, eta, w, c));
    return rcpp_result_gen;
END_RCPP
}
// sdll_lla
arma::mat sdll_lla(const arma::vec& b, const arma::mat& Z, const arma::mat& D, const arma::mat& V, const arma::rowvec& K, const arma::vec& l0u, const arma::vec& phi, const arma::vec& eta, const arma::vec& w);
RcppExport SEXP _JEL_sdll_lla(SEXP bSEXP, SEXP ZSEXP, SEXP DSEXP, SEXP VSEXP, SEXP KSEXP, SEXP l0uSEXP, SEXP phiSEXP, SEXP etaSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(sdll_lla(b, Z, D, V, K, l0u, phi, eta, w));
    return rcpp_result_gen;
END_RCPP
}
// ll_lla_tv
double ll_lla_tv(const arma::vec& b, const arma::colvec& Y, const arma::mat& Z, const arma::mat& V, const arma::mat& D, const int mi, const arma::rowvec& K, const int Delta, const double l0i, const arma::rowvec& l0u, const arma::vec& phi, const arma::mat& etaBB, const arma::vec& w, const arma::vec& c);
RcppExport SEXP _JEL_ll_lla_tv(SEXP bSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP VSEXP, SEXP DSEXP, SEXP miSEXP, SEXP KSEXP, SEXP DeltaSEXP, SEXP l0iSEXP, SEXP l0uSEXP, SEXP phiSEXP, SEXP etaBBSEXP, SEXP wSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const int >::type mi(miSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< const double >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type etaBB(etaBBSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(ll_lla_tv(b, Y, Z, V, D, mi, K, Delta, l0i, l0u, phi, etaBB, w, c));
    return rcpp_result_gen;
END_RCPP
}
// gradll_lla_tv
arma::colvec gradll_lla_tv(const arma::vec& b, const arma::colvec& Y, const arma::mat& Z, const arma::mat& V, const arma::mat& D, const int mi, const arma::rowvec& K, const int Delta, const double l0i, const arma::rowvec& l0u, const arma::vec& phi, const arma::mat& etaBB, const arma::vec& w, const arma::vec& c);
RcppExport SEXP _JEL_gradll_lla_tv(SEXP bSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP VSEXP, SEXP DSEXP, SEXP miSEXP, SEXP KSEXP, SEXP DeltaSEXP, SEXP l0iSEXP, SEXP l0uSEXP, SEXP phiSEXP, SEXP etaBBSEXP, SEXP wSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const int >::type mi(miSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< const double >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type etaBB(etaBBSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(gradll_lla_tv(b, Y, Z, V, D, mi, K, Delta, l0i, l0u, phi, etaBB, w, c));
    return rcpp_result_gen;
END_RCPP
}
// sdll_lla_tv
arma::mat sdll_lla_tv(const arma::vec& b, const arma::mat& Z, const arma::mat& D, const arma::mat& V, const arma::rowvec& K, const arma::vec& l0u, const arma::vec& phi, const arma::mat& etaBB, const arma::vec& w);
RcppExport SEXP _JEL_sdll_lla_tv(SEXP bSEXP, SEXP ZSEXP, SEXP DSEXP, SEXP VSEXP, SEXP KSEXP, SEXP l0uSEXP, SEXP phiSEXP, SEXP etaBBSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type etaBB(etaBBSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(sdll_lla_tv(b, Z, D, V, K, l0u, phi, etaBB, w));
    return rcpp_result_gen;
END_RCPP
}
// ll_tv
double ll_tv(arma::vec b, const arma::colvec Y, const arma::mat X, const arma::mat Z, const arma::mat V, const arma::mat D, int mi, const arma::rowvec K, const int Delta, const double l0i, const arma::colvec l0u, const arma::vec beta, const arma::vec phi, const arma::mat etaBB, const int nK, const int q);
RcppExport SEXP _JEL_ll_tv(SEXP bSEXP, SEXP YSEXP, SEXP XSEXP, SEXP ZSEXP, SEXP VSEXP, SEXP DSEXP, SEXP miSEXP, SEXP KSEXP, SEXP DeltaSEXP, SEXP l0iSEXP, SEXP l0uSEXP, SEXP betaSEXP, SEXP phiSEXP, SEXP etaBBSEXP, SEXP nKSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type mi(miSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< const double >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type etaBB(etaBBSEXP);
    Rcpp::traits::input_parameter< const int >::type nK(nKSEXP);
    Rcpp::traits::input_parameter< const int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(ll_tv(b, Y, X, Z, V, D, mi, K, Delta, l0i, l0u, beta, phi, etaBB, nK, q));
    return rcpp_result_gen;
END_RCPP
}
// elementwise_multiply
arma::mat elementwise_multiply(const arma::mat mat, const arma::vec vec);
RcppExport SEXP _JEL_elementwise_multiply(SEXP matSEXP, SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(elementwise_multiply(mat, vec));
    return rcpp_result_gen;
END_RCPP
}
// gradll_tv
arma::colvec gradll_tv(arma::vec b, const arma::colvec Y, const arma::mat X, const arma::mat Z, const arma::mat V, const arma::mat D, int mi, const arma::rowvec K, const int Delta, const double l0i, const arma::colvec l0u, const arma::vec beta, const arma::vec phi, const arma::mat etaBB, const int nK, const int q);
RcppExport SEXP _JEL_gradll_tv(SEXP bSEXP, SEXP YSEXP, SEXP XSEXP, SEXP ZSEXP, SEXP VSEXP, SEXP DSEXP, SEXP miSEXP, SEXP KSEXP, SEXP DeltaSEXP, SEXP l0iSEXP, SEXP l0uSEXP, SEXP betaSEXP, SEXP phiSEXP, SEXP etaBBSEXP, SEXP nKSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type mi(miSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< const double >::type l0i(l0iSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type etaBB(etaBBSEXP);
    Rcpp::traits::input_parameter< const int >::type nK(nKSEXP);
    Rcpp::traits::input_parameter< const int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(gradll_tv(b, Y, X, Z, V, D, mi, K, Delta, l0i, l0u, beta, phi, etaBB, nK, q));
    return rcpp_result_gen;
END_RCPP
}
// sdll_tv
arma::mat sdll_tv(arma::vec b, const arma::mat Z, const arma::mat D, const arma::mat V, const arma::rowvec K, const arma::vec l0u, const arma::vec phi, const arma::mat etaBB, const int nK);
RcppExport SEXP _JEL_sdll_tv(SEXP bSEXP, SEXP ZSEXP, SEXP DSEXP, SEXP VSEXP, SEXP KSEXP, SEXP l0uSEXP, SEXP phiSEXP, SEXP etaBBSEXP, SEXP nKSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type etaBB(etaBBSEXP);
    Rcpp::traits::input_parameter< const int >::type nK(nKSEXP);
    rcpp_result_gen = Rcpp::wrap(sdll_tv(b, Z, D, V, K, l0u, phi, etaBB, nK));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_e
double rcpp_e(const arma::colvec Yik, const arma::mat Xik, const arma::mat Zik, const arma::vec beta, const arma::vec b);
RcppExport SEXP _JEL_rcpp_e(SEXP YikSEXP, SEXP XikSEXP, SEXP ZikSEXP, SEXP betaSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec >::type Yik(YikSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Xik(XikSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Zik(ZikSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_e(Yik, Xik, Zik, beta, b));
    return rcpp_result_gen;
END_RCPP
}
// Ee
NumericVector Ee(const Rcpp::List Y, const Rcpp::List X, const Rcpp::List Z, const arma::mat beta, const Rcpp::List b, const Rcpp::List bbT, const int ids, const int K);
RcppExport SEXP _JEL_Ee(SEXP YSEXP, SEXP XSEXP, SEXP ZSEXP, SEXP betaSEXP, SEXP bSEXP, SEXP bbTSEXP, SEXP idsSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type b(bSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type bbT(bbTSEXP);
    Rcpp::traits::input_parameter< const int >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< const int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(Ee(Y, X, Z, beta, b, bbT, ids, K));
    return rcpp_result_gen;
END_RCPP
}
// Eb
List Eb(const List Y, const List X, const List Z, const List V, const arma::mat D, const arma::vec beta, const int ids);
RcppExport SEXP _JEL_Eb(SEXP YSEXP, SEXP XSEXP, SEXP ZSEXP, SEXP VSEXP, SEXP DSEXP, SEXP betaSEXP, SEXP idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const List >::type X(XSEXP);
    Rcpp::traits::input_parameter< const List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const List >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const int >::type ids(idsSEXP);
    rcpp_result_gen = Rcpp::wrap(Eb(Y, X, Z, V, D, beta, ids));
    return rcpp_result_gen;
END_RCPP
}
// covb
List covb(const List Z, const List V, const arma::mat Dinv, const int ids);
RcppExport SEXP _JEL_covb(SEXP ZSEXP, SEXP VSEXP, SEXP DinvSEXP, SEXP idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const List >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Dinv(DinvSEXP);
    Rcpp::traits::input_parameter< const int >::type ids(idsSEXP);
    rcpp_result_gen = Rcpp::wrap(covb(Z, V, Dinv, ids));
    return rcpp_result_gen;
END_RCPP
}
// EbbT
List EbbT(const List b, const List Sigma, const int ids);
RcppExport SEXP _JEL_EbbT(SEXP bSEXP, SEXP SigmaSEXP, SEXP idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List >::type b(bSEXP);
    Rcpp::traits::input_parameter< const List >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< const int >::type ids(idsSEXP);
    rcpp_result_gen = Rcpp::wrap(EbbT(b, Sigma, ids));
    return rcpp_result_gen;
END_RCPP
}
// betaRHS
List betaRHS(const List X, const List Y, const List Z, const List b, const int ids);
RcppExport SEXP _JEL_betaRHS(SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP bSEXP, SEXP idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List >::type X(XSEXP);
    Rcpp::traits::input_parameter< const List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const List >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const List >::type b(bSEXP);
    Rcpp::traits::input_parameter< const int >::type ids(idsSEXP);
    rcpp_result_gen = Rcpp::wrap(betaRHS(X, Y, Z, b, ids));
    return rcpp_result_gen;
END_RCPP
}
// update_lambda
List update_lambda(NumericVector Es_exp, List l0u, NumericVector l0, int n);
RcppExport SEXP _JEL_update_lambda(SEXP Es_expSEXP, SEXP l0uSEXP, SEXP l0SEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Es_exp(Es_expSEXP);
    Rcpp::traits::input_parameter< List >::type l0u(l0uSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type l0(l0SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(update_lambda(Es_exp, l0u, l0, n));
    return rcpp_result_gen;
END_RCPP
}
// update_lambda_tv
List update_lambda_tv(List Es_exp, NumericVector l0, int n);
RcppExport SEXP _JEL_update_lambda_tv(SEXP Es_expSEXP, SEXP l0SEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Es_exp(Es_expSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type l0(l0SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(update_lambda_tv(Es_exp, l0, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_JEL_calc_mu_surv", (DL_FUNC) &_JEL_calc_mu_surv, 10},
    {"_JEL_calc_Sigma2_surv", (DL_FUNC) &_JEL_calc_Sigma2_surv, 5},
    {"_JEL_calc_mu_surv_noX", (DL_FUNC) &_JEL_calc_mu_surv_noX, 8},
    {"_JEL_calc_Sigma2_surv_noX", (DL_FUNC) &_JEL_calc_Sigma2_surv_noX, 4},
    {"_JEL_calc_mu_surv_noX_tv", (DL_FUNC) &_JEL_calc_mu_surv_noX_tv, 8},
    {"_JEL_calc_Sigma2_surv_noX_tv", (DL_FUNC) &_JEL_calc_Sigma2_surv_noX_tv, 4},
    {"_JEL_Eetaphi_lla_tv", (DL_FUNC) &_JEL_Eetaphi_lla_tv, 17},
    {"_JEL_Setaphi_lla_tv", (DL_FUNC) &_JEL_Setaphi_lla_tv, 18},
    {"_JEL_Hetaphi_lla_tv", (DL_FUNC) &_JEL_Hetaphi_lla_tv, 18},
    {"_JEL_calc_mu_surv_tv", (DL_FUNC) &_JEL_calc_mu_surv_tv, 10},
    {"_JEL_calc_Sigma2_surv_tv", (DL_FUNC) &_JEL_calc_Sigma2_surv_tv, 5},
    {"_JEL_subtract_one_from_uvec", (DL_FUNC) &_JEL_subtract_one_from_uvec, 1},
    {"_JEL_calc_inv_omega_kernel", (DL_FUNC) &_JEL_calc_inv_omega_kernel, 3},
    {"_JEL_calc_Sigma_longK", (DL_FUNC) &_JEL_calc_Sigma_longK, 3},
    {"_JEL_calc_mu_longK_noX", (DL_FUNC) &_JEL_calc_mu_longK_noX, 5},
    {"_JEL_calc_Ee_kernel", (DL_FUNC) &_JEL_calc_Ee_kernel, 4},
    {"_JEL_calc_M1_M2_Hadamard", (DL_FUNC) &_JEL_calc_M1_M2_Hadamard, 2},
    {"_JEL_calc_M1_M2_Hadamard_a", (DL_FUNC) &_JEL_calc_M1_M2_Hadamard_a, 4},
    {"_JEL_calc_M1_M2_M3_Hadamard", (DL_FUNC) &_JEL_calc_M1_M2_M3_Hadamard, 4},
    {"_JEL_calc_M1_a_M2_Hadamard", (DL_FUNC) &_JEL_calc_M1_a_M2_Hadamard, 4},
    {"_JEL_calc_M1timesM2v", (DL_FUNC) &_JEL_calc_M1timesM2v, 3},
    {"_JEL_calc_MVND", (DL_FUNC) &_JEL_calc_MVND, 3},
    {"_JEL_calc_M_v", (DL_FUNC) &_JEL_calc_M_v, 2},
    {"_JEL_calc_VB", (DL_FUNC) &_JEL_calc_VB, 3},
    {"_JEL_calc_VY", (DL_FUNC) &_JEL_calc_VY, 3},
    {"_JEL_calc_bi_st", (DL_FUNC) &_JEL_calc_bi_st, 3},
    {"_JEL_calc_expM2", (DL_FUNC) &_JEL_calc_expM2, 1},
    {"_JEL_calc_muB", (DL_FUNC) &_JEL_calc_muB, 6},
    {"_JEL_calc_muBMult", (DL_FUNC) &_JEL_calc_muBMult, 4},
    {"_JEL_calc_mult_rowsum1", (DL_FUNC) &_JEL_calc_mult_rowsum1, 4},
    {"_JEL_calc_mult_rowsum2", (DL_FUNC) &_JEL_calc_mult_rowsum2, 4},
    {"_JEL_calc_mult_rowsum3", (DL_FUNC) &_JEL_calc_mult_rowsum3, 5},
    {"_JEL_calc_rowsum", (DL_FUNC) &_JEL_calc_rowsum, 2},
    {"_JEL_calc_rowsum_mult", (DL_FUNC) &_JEL_calc_rowsum_mult, 3},
    {"_JEL_calc_tapply_vect_sum", (DL_FUNC) &_JEL_calc_tapply_vect_sum, 2},
    {"_JEL_calc_v_a", (DL_FUNC) &_JEL_calc_v_a, 2},
    {"_JEL_Esurv", (DL_FUNC) &_JEL_Esurv, 8},
    {"_JEL_Esurv_exp", (DL_FUNC) &_JEL_Esurv_exp, 8},
    {"_JEL_Eetaphi", (DL_FUNC) &_JEL_Eetaphi, 15},
    {"_JEL_Setaphi", (DL_FUNC) &_JEL_Setaphi, 16},
    {"_JEL_Setaphi_perobs", (DL_FUNC) &_JEL_Setaphi_perobs, 16},
    {"_JEL_Hetaphi", (DL_FUNC) &_JEL_Hetaphi, 16},
    {"_JEL_scaleMatricesByEta", (DL_FUNC) &_JEL_scaleMatricesByEta, 2},
    {"_JEL_createResultMatrix", (DL_FUNC) &_JEL_createResultMatrix, 2},
    {"_JEL_etaBBs_compute", (DL_FUNC) &_JEL_etaBBs_compute, 3},
    {"_JEL_Esurv_tv", (DL_FUNC) &_JEL_Esurv_tv, 8},
    {"_JEL_Esurv_exp_tv", (DL_FUNC) &_JEL_Esurv_exp_tv, 8},
    {"_JEL_Esurv_exp_t", (DL_FUNC) &_JEL_Esurv_exp_t, 8},
    {"_JEL_Eetaphi_t", (DL_FUNC) &_JEL_Eetaphi_t, 18},
    {"_JEL_Setaphi_t", (DL_FUNC) &_JEL_Setaphi_t, 19},
    {"_JEL_Hetaphi_t", (DL_FUNC) &_JEL_Hetaphi_t, 19},
    {"_JEL_fast_lapply_length", (DL_FUNC) &_JEL_fast_lapply_length, 3},
    {"_JEL_fast_rbind_lapply_outerprod", (DL_FUNC) &_JEL_fast_rbind_lapply_outerprod, 1},
    {"_JEL_ll", (DL_FUNC) &_JEL_ll, 16},
    {"_JEL_gradll", (DL_FUNC) &_JEL_gradll, 16},
    {"_JEL_sdll", (DL_FUNC) &_JEL_sdll, 9},
    {"_JEL_ll_lla", (DL_FUNC) &_JEL_ll_lla, 14},
    {"_JEL_gradll_lla", (DL_FUNC) &_JEL_gradll_lla, 14},
    {"_JEL_sdll_lla", (DL_FUNC) &_JEL_sdll_lla, 9},
    {"_JEL_ll_lla_tv", (DL_FUNC) &_JEL_ll_lla_tv, 14},
    {"_JEL_gradll_lla_tv", (DL_FUNC) &_JEL_gradll_lla_tv, 14},
    {"_JEL_sdll_lla_tv", (DL_FUNC) &_JEL_sdll_lla_tv, 9},
    {"_JEL_ll_tv", (DL_FUNC) &_JEL_ll_tv, 16},
    {"_JEL_elementwise_multiply", (DL_FUNC) &_JEL_elementwise_multiply, 2},
    {"_JEL_gradll_tv", (DL_FUNC) &_JEL_gradll_tv, 16},
    {"_JEL_sdll_tv", (DL_FUNC) &_JEL_sdll_tv, 9},
    {"_JEL_rcpp_e", (DL_FUNC) &_JEL_rcpp_e, 5},
    {"_JEL_Ee", (DL_FUNC) &_JEL_Ee, 8},
    {"_JEL_Eb", (DL_FUNC) &_JEL_Eb, 7},
    {"_JEL_covb", (DL_FUNC) &_JEL_covb, 4},
    {"_JEL_EbbT", (DL_FUNC) &_JEL_EbbT, 3},
    {"_JEL_betaRHS", (DL_FUNC) &_JEL_betaRHS, 5},
    {"_JEL_update_lambda", (DL_FUNC) &_JEL_update_lambda, 4},
    {"_JEL_update_lambda_tv", (DL_FUNC) &_JEL_update_lambda_tv, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_JEL(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
