# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_mu_surv <- function(X, Y, Z, inv_omega, K, D, beta, phi, eta, nK) {
    .Call(`_JEL_calc_mu_surv`, X, Y, Z, inv_omega, K, D, beta, phi, eta, nK)
}

calc_Sigma2_surv <- function(X, Z, inv_omega, D, eta) {
    .Call(`_JEL_calc_Sigma2_surv`, X, Z, inv_omega, D, eta)
}

calc_mu_surv_noX <- function(Y, Z, inv_omega, K, D, phi, eta, c) {
    .Call(`_JEL_calc_mu_surv_noX`, Y, Z, inv_omega, K, D, phi, eta, c)
}

calc_Sigma2_surv_noX <- function(Z, inv_omega, D, eta) {
    .Call(`_JEL_calc_Sigma2_surv_noX`, Z, inv_omega, D, eta)
}

calc_mu_surv_noX_tv <- function(Y, Z, inv_omega, K, D, phi, etaBB, c) {
    .Call(`_JEL_calc_mu_surv_noX_tv`, Y, Z, inv_omega, K, D, phi, etaBB, c)
}

calc_Sigma2_surv_noX_tv <- function(Z, inv_omega, D, etaBB) {
    .Call(`_JEL_calc_Sigma2_surv_noX_tv`, Z, inv_omega, D, etaBB)
}

Eetaphi_lla_tv <- function(etaphi, Y, Z, inv_omega, K, D, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, BBi, etaInd, c_list) {
    .Call(`_JEL_Eetaphi_lla_tv`, etaphi, Y, Z, inv_omega, K, D, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, BBi, etaInd, c_list)
}

Setaphi_lla_tv <- function(etaphi, Y, Z, inv_omega, K, D, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, BBi, etaInd, eps, c_list) {
    .Call(`_JEL_Setaphi_lla_tv`, etaphi, Y, Z, inv_omega, K, D, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, BBi, etaInd, eps, c_list)
}

Hetaphi_lla_tv <- function(etaphi, Y, Z, inv_omega, K, D, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, BBi, etaInd, eps, c_list) {
    .Call(`_JEL_Hetaphi_lla_tv`, etaphi, Y, Z, inv_omega, K, D, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, BBi, etaInd, eps, c_list)
}

calc_mu_surv_tv <- function(X, Y, Z, inv_omega, K, D, beta, phi, etaBB, nK) {
    .Call(`_JEL_calc_mu_surv_tv`, X, Y, Z, inv_omega, K, D, beta, phi, etaBB, nK)
}

calc_Sigma2_surv_tv <- function(X, Z, inv_omega, D, etaBB) {
    .Call(`_JEL_calc_Sigma2_surv_tv`, X, Z, inv_omega, D, etaBB)
}

subtract_one_from_uvec <- function(vec) {
    .Call(`_JEL_subtract_one_from_uvec`, vec)
}

calc_inv_omega_kernel <- function(mi_list, var_e, w_stack_list) {
    .Call(`_JEL_calc_inv_omega_kernel`, mi_list, var_e, w_stack_list)
}

calc_Sigma_longK <- function(Z_list, S_list, nK) {
    .Call(`_JEL_calc_Sigma_longK`, Z_list, S_list, nK)
}

calc_mu_longK_noX <- function(Y_list, Z_list, b_list, b_inds, nK) {
    .Call(`_JEL_calc_mu_longK_noX`, Y_list, Z_list, b_list, b_inds, nK)
}

calc_Ee_kernel <- function(mu_list, Sigma_longK, w_longK, nK) {
    .Call(`_JEL_calc_Ee_kernel`, mu_list, Sigma_longK, w_longK, nK)
}

calc_M1_M2_Hadamard <- function(M1, M2) {
    invisible(.Call(`_JEL_calc_M1_M2_Hadamard`, M1, M2))
}

calc_M1_M2_Hadamard_a <- function(A1, A2, v3, a) {
    .Call(`_JEL_calc_M1_M2_Hadamard_a`, A1, A2, v3, a)
}

calc_M1_M2_M3_Hadamard <- function(M1, M2, M3, v) {
    invisible(.Call(`_JEL_calc_M1_M2_M3_Hadamard`, M1, M2, M3, v))
}

calc_M1_a_M2_Hadamard <- function(M1, M2, a, v) {
    invisible(.Call(`_JEL_calc_M1_a_M2_Hadamard`, M1, M2, a, v))
}

calc_M1timesM2v <- function(M1, M2, v) {
    .Call(`_JEL_calc_M1timesM2v`, M1, M2, v)
}

calc_MVND <- function(x, mu, K) {
    .Call(`_JEL_calc_MVND`, x, mu, K)
}

calc_M_v <- function(v, M) {
    .Call(`_JEL_calc_M_v`, v, M)
}

calc_VB <- function(M1, M2, M3) {
    .Call(`_JEL_calc_VB`, M1, M2, M3)
}

calc_VY <- function(M, A, b) {
    .Call(`_JEL_calc_VY`, M, A, b)
}

calc_bi_st <- function(v0, m, M) {
    .Call(`_JEL_calc_bi_st`, v0, m, M)
}

calc_expM2 <- function(A) {
    invisible(.Call(`_JEL_calc_expM2`, A))
}

calc_muB <- function(BSold, VY, Xst, Zst, Yst, betaold) {
    .Call(`_JEL_calc_muB`, BSold, VY, Xst, Zst, Yst, betaold)
}

calc_muBMult <- function(BSold, VY, BTg, Yst) {
    .Call(`_JEL_calc_muBMult`, BSold, VY, BTg, Yst)
}

calc_mult_rowsum1 <- function(v, u, M, A) {
    .Call(`_JEL_calc_mult_rowsum1`, v, u, M, A)
}

calc_mult_rowsum2 <- function(v, L, M, A) {
    .Call(`_JEL_calc_mult_rowsum2`, v, L, M, A)
}

calc_mult_rowsum3 <- function(v, B, M, A, ncb2) {
    .Call(`_JEL_calc_mult_rowsum3`, v, B, M, A, ncb2)
}

calc_rowsum <- function(v, M) {
    .Call(`_JEL_calc_rowsum`, v, M)
}

calc_rowsum_mult <- function(v, u, M) {
    .Call(`_JEL_calc_rowsum_mult`, v, u, M)
}

calc_tapply_vect_sum <- function(v1, v2) {
    .Call(`_JEL_calc_tapply_vect_sum`, v1, v2)
}

calc_v_a <- function(v, a) {
    invisible(.Call(`_JEL_calc_v_a`, v, a))
}

Esurv <- function(w, v, mu, variance, mu_new, variance_new, l0i, l0u) {
    .Call(`_JEL_Esurv`, w, v, mu, variance, mu_new, variance_new, l0i, l0u)
}

Esurv_exp <- function(w, v, mu, variance, mu_new, variance_new, l0i, l0u) {
    .Call(`_JEL_Esurv_exp`, w, v, mu, variance, mu_new, variance_new, l0i, l0u)
}

Eetaphi <- function(etaphi, Y, Z, inv_omega, K, D, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, c_list) {
    .Call(`_JEL_Eetaphi`, etaphi, Y, Z, inv_omega, K, D, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, c_list)
}

Setaphi <- function(etaphi, Y, Z, inv_omega, K, D, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, eps, c_list) {
    .Call(`_JEL_Setaphi`, etaphi, Y, Z, inv_omega, K, D, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, eps, c_list)
}

Setaphi_perobs <- function(etaphi, Y, Z, inv_omega, K, D, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, eps, c_list) {
    .Call(`_JEL_Setaphi_perobs`, etaphi, Y, Z, inv_omega, K, D, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, eps, c_list)
}

Hetaphi <- function(etaphi, Y, Z, inv_omega, K, D, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, eps, c_list) {
    .Call(`_JEL_Hetaphi`, etaphi, Y, Z, inv_omega, K, D, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, eps, c_list)
}

scaleMatricesByEta <- function(BBi, eta) {
    .Call(`_JEL_scaleMatricesByEta`, BBi, eta)
}

createResultMatrix <- function(A, etaInd) {
    .Call(`_JEL_createResultMatrix`, A, etaInd)
}

etaBBs_compute <- function(BBi, eta, etaInd) {
    .Call(`_JEL_etaBBs_compute`, BBi, eta, etaInd)
}

Esurv_tv <- function(w, v, mu, variance, mu_new, variance_new, l0i, l0u) {
    .Call(`_JEL_Esurv_tv`, w, v, mu, variance, mu_new, variance_new, l0i, l0u)
}

Esurv_exp_tv <- function(w, v, mu, variance, mu_new, variance_new, l0i, l0u) {
    .Call(`_JEL_Esurv_exp_tv`, w, v, mu, variance, mu_new, variance_new, l0i, l0u)
}

Esurv_exp_t <- function(w, v, mu, variance, mu_new, variance_new, l0i, l0u) {
    .Call(`_JEL_Esurv_exp_t`, w, v, mu, variance, mu_new, variance_new, l0i, l0u)
}

Eetaphi_t <- function(etaphi, X, Y, Z, inv_omega, K, D, beta, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, BBi, etaInd) {
    .Call(`_JEL_Eetaphi_t`, etaphi, X, Y, Z, inv_omega, K, D, beta, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, BBi, etaInd)
}

Setaphi_t <- function(etaphi, X, Y, Z, inv_omega, K, D, beta, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, BBi, etaInd, eps) {
    .Call(`_JEL_Setaphi_t`, etaphi, X, Y, Z, inv_omega, K, D, beta, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, BBi, etaInd, eps)
}

Hetaphi_t <- function(etaphi, X, Y, Z, inv_omega, K, D, beta, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, BBi, etaInd, eps) {
    .Call(`_JEL_Hetaphi_t`, etaphi, X, Y, Z, inv_omega, K, D, beta, l0i, l0u, Di, nK, w, v, mu_surv, Sigma2_surv, BBi, etaInd, eps)
}

fast_lapply_length <- function(input1, input2, Ind) {
    .Call(`_JEL_fast_lapply_length`, input1, input2, Ind)
}

fast_rbind_lapply_outerprod <- function(input) {
    .Call(`_JEL_fast_rbind_lapply_outerprod`, input)
}

ll <- function(b, Y, X, Z, V, D, mi, K, Delta, l0i, l0u, beta, phi, eta, nK, q) {
    .Call(`_JEL_ll`, b, Y, X, Z, V, D, mi, K, Delta, l0i, l0u, beta, phi, eta, nK, q)
}

gradll <- function(b, Y, X, Z, V, D, mi, K, Delta, l0i, l0u, beta, phi, eta, nK, q) {
    .Call(`_JEL_gradll`, b, Y, X, Z, V, D, mi, K, Delta, l0i, l0u, beta, phi, eta, nK, q)
}

sdll <- function(b, Z, D, V, K, l0u, phi, eta, nK) {
    .Call(`_JEL_sdll`, b, Z, D, V, K, l0u, phi, eta, nK)
}

ll_lla <- function(b, Y, Z, V, D, mi, K, Delta, l0i, l0u, phi, eta, w, c) {
    .Call(`_JEL_ll_lla`, b, Y, Z, V, D, mi, K, Delta, l0i, l0u, phi, eta, w, c)
}

gradll_lla <- function(b, Y, Z, V, D, mi, K, Delta, l0i, l0u, phi, eta, w, c) {
    .Call(`_JEL_gradll_lla`, b, Y, Z, V, D, mi, K, Delta, l0i, l0u, phi, eta, w, c)
}

sdll_lla <- function(b, Z, D, V, K, l0u, phi, eta, w) {
    .Call(`_JEL_sdll_lla`, b, Z, D, V, K, l0u, phi, eta, w)
}

ll_lla_tv <- function(b, Y, Z, V, D, mi, K, Delta, l0i, l0u, phi, etaBB, w, c) {
    .Call(`_JEL_ll_lla_tv`, b, Y, Z, V, D, mi, K, Delta, l0i, l0u, phi, etaBB, w, c)
}

gradll_lla_tv <- function(b, Y, Z, V, D, mi, K, Delta, l0i, l0u, phi, etaBB, w, c) {
    .Call(`_JEL_gradll_lla_tv`, b, Y, Z, V, D, mi, K, Delta, l0i, l0u, phi, etaBB, w, c)
}

sdll_lla_tv <- function(b, Z, D, V, K, l0u, phi, etaBB, w) {
    .Call(`_JEL_sdll_lla_tv`, b, Z, D, V, K, l0u, phi, etaBB, w)
}

ll_tv <- function(b, Y, X, Z, V, D, mi, K, Delta, l0i, l0u, beta, phi, etaBB, nK, q) {
    .Call(`_JEL_ll_tv`, b, Y, X, Z, V, D, mi, K, Delta, l0i, l0u, beta, phi, etaBB, nK, q)
}

elementwise_multiply <- function(mat, vec) {
    .Call(`_JEL_elementwise_multiply`, mat, vec)
}

gradll_tv <- function(b, Y, X, Z, V, D, mi, K, Delta, l0i, l0u, beta, phi, etaBB, nK, q) {
    .Call(`_JEL_gradll_tv`, b, Y, X, Z, V, D, mi, K, Delta, l0i, l0u, beta, phi, etaBB, nK, q)
}

sdll_tv <- function(b, Z, D, V, K, l0u, phi, etaBB, nK) {
    .Call(`_JEL_sdll_tv`, b, Z, D, V, K, l0u, phi, etaBB, nK)
}

rcpp_e <- function(Yik, Xik, Zik, beta, b) {
    .Call(`_JEL_rcpp_e`, Yik, Xik, Zik, beta, b)
}

Ee <- function(Y, X, Z, beta, b, bbT, ids, K) {
    .Call(`_JEL_Ee`, Y, X, Z, beta, b, bbT, ids, K)
}

Eb <- function(Y, X, Z, V, D, beta, ids) {
    .Call(`_JEL_Eb`, Y, X, Z, V, D, beta, ids)
}

covb <- function(Z, V, Dinv, ids) {
    .Call(`_JEL_covb`, Z, V, Dinv, ids)
}

EbbT <- function(b, Sigma, ids) {
    .Call(`_JEL_EbbT`, b, Sigma, ids)
}

betaRHS <- function(X, Y, Z, b, ids) {
    .Call(`_JEL_betaRHS`, X, Y, Z, b, ids)
}

update_lambda <- function(Es_exp, l0u, l0, n) {
    .Call(`_JEL_update_lambda`, Es_exp, l0u, l0, n)
}

update_lambda_tv <- function(Es_exp, l0, n) {
    .Call(`_JEL_update_lambda_tv`, Es_exp, l0, n)
}

